const secret = 'rivaldo';
const headerToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDE5N2VjYmU5NTY4MmExOGFjNDQ3MiIsInVzZXJuYW1lIjoidGluZGVja2VuIiwic2NvcGUiOiJhZG1pbiIsImlhdCI6MTU1ODYyMjMzNiwiZXhwIjoxNTU4NjY1NTM2fQ.Bz5JTOXEbAsI4SPWKFG9qbhRLAO8-a4qmJMdUrYyNqE'

module.exports = { secret, headerToken }