const secret = 'rivaldo';
const headerToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZjRjMjFkZjM2NDIxNTJhOGQwZTBlNCIsIm5hbWUiOiJ0aW5kZWNrZW4iLCJlbWFpbCI6InRpbmRlY2tlbkBnbWFpbC5jb20iLCJzY29wZSI6ImFkbWluIiwiaWF0IjoxNTY5MjA4ODc3LCJleHAiOjE1NjkyNTIwNzd9.R1n7oGhhdyCviQMCbhkaM2c8rg7lMK6iaIZOyolfT4o'

module.exports = { secret, headerToken }
