const secret = 'rivaldo';
const headerToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjY2ZhMTA4ZWZmMWY1Mjg0MDM0OTkzOSIsInVzZXJuYW1lIjoidGluZGVja2VuIiwic2NvcGUiOiJhZG1pbiIsImlhdCI6MTU1ODA2Nzg4OSwiZXhwIjoxNTU4MTExMDg5fQ.65KqR9WWJiCKJI4toGJwovUvvEwPpd1964UpzvVYy6U'

module.exports = { secret, headerToken }